# Copyright 2020-2025 NXP

"""TODO:summary line."""
import json
import logging
import os
import sys
from copy import deepcopy
from datetime import date

import lz4.frame
from memtool.__version__ import __version__

from .constants import Const

logger = logging.getLogger(__name__)


def get_bin_data(filename: str, compress: bool = False):  # type: ignore
    """Load data from binary file.

    @param filename: absolute path to the binary file
    @param compress: flag indicating if the file should be compressed
    @return: a bytearray with file data and the number of bytes read from file
    """
    file_size = os.path.getsize(filename)
    file_data = bytearray(file_size)
    with open(filename, 'rb') as f:
        file_data = f.read()  # type: ignore
    if compress:
        file_data = lz4.frame.compress(file_data, Const.LZ4_COMPRESSION_LEVEL)
        compressed_file_size = len(file_data)
    if compress:
        return file_data, file_size, compressed_file_size
    return file_data, file_size


def align(value: int, mask: int) -> int:
    """Align value.

    @param value:
    @param mask:
    @return: aligned value
    """
    return (value + (mask - 1)) & (~(mask - 1))


def aligned_incr(counter: int, increment: int, alignment: int) -> int:
    """Increment and align."""
    return (counter + increment + alignment - 1) & ~(alignment - 1)


def swap_32(x):  # type: ignore
    """Swaps the bytes of a 32-bit integer number.

    @type x: int
    @param x: 32-bit integer number to swap
    @rtype: int
    @return: the swapped value of the provided integer
    """
    return ((x << 24) & 0xFF000000) | ((x << 8) & 0x00FF0000) | ((x >> 8) & 0x0000FF00) | ((x >> 24) & 0x000000FF)


def add_file_to_params(file: str, params: dict) -> dict:
    """Add params stored in json files.

    @param file: file to analyse
    @param params: dict to add params and corresponding values into
    @return: updated dict
    """
    logging.getLogger(__name__).info(' *****%s', file)
    if file.endswith(".json"):
        with open(file, "rt", encoding="utf-8") as f:
            try:
                _params = json.load(f)
                process_dict(_params)
                params = merge_dict(params, _params)
            except Exception as ex:
                exit_script(ex)
    return params


def merge_dict(d1: dict, d2: dict, append_val_to_list_if_unique: bool = False) -> dict:
    """Recursively merge 2 dictionaries.

    In case of a clash, values in the second one (d2) have priority over the first one.
    Returns a new dictionary that contains the merged dictionaries.
    @type d1: dict
    @param d1: first dictionary
    @type d2: dict
    @param d2: second dictionary, having priority over the first one in case
        of key clashes.
    @type append_val_to_list_if_unique: bool
    @param append_val_to_list_if_unique: If 'True' it appends unique values to list
    if values are list type, otherwise values from second dictionary have priority.
    @rtype: dict
    @return: a combination of the 1st and 2nd dictionaries
    """
    d3 = deepcopy(d1)
    for key in d2:
        if key in d3 and isinstance(d3[key], dict) and isinstance(d2[key], dict):
            d3[key] = merge_dict(d1[key], d2[key])
        elif key in d3 and isinstance(d3[key], list) and isinstance(d2[key], list):
            if append_val_to_list_if_unique:
                for value in d2[key]:
                    if value not in d3[key]:
                        d3[key].append(value)
            else:
                d3[key] = d2[key]
        else:
            d3[key] = d2[key]
    return d3


def process_dict(d: dict):  # type: ignore
    """Update values to the intended meaning.

    Eg: 'True'->True, 'False'->False
    Temporary workaround until proper json is generated by the higher levels
    """
    for k, v in d.items():
        if isinstance(v, str):
            d[k] = {'True': True, 'False': False}.get(v, v)
        elif isinstance(v, dict):
            process_dict(v)


def exit_script(message):  # type: ignore
    """Log exception and exit.

    @param message: exception message
    """
    logging.getLogger(__name__).error(message)
    print(Const.DONE_MARKER)
    sys.exit(1)


def write_file_content(file_path: str, file_content: str):  # type: ignore
    """It writes a file content to a specific file location.

    It creates file if it does not exist or overwrites it if exists.
    @param file_path: File path.
    @param file_content: File content to be written to file path.
    """
    try:
        with open(file_path, "w", encoding="utf-8", newline='\n') as f:
            f.write(file_content)
    except Exception as ex:
        logger.error(ex)


def get_syms_file_path(app_path: str) -> str:
    """Get symbolics file path that corresponds to the given binary.

    @param app_path: application file path
    @rtype: str
    @return: symbolics file path
    """
    app_file_name, app_file_extension = os.path.splitext(app_path)
    return app_file_name + ".syms"


def get_current_year() -> int:
    """It gets current year."""
    return date.today().year


def get_current_version() -> int:
    """It gets current version of DDR Tool."""
    return __version__  # type: ignore


def is_hex(input_str: str):  # type: ignore
    """Check if input string represents a hex number."""
    try:
        int(input_str, 16)
    except ValueError:
        return False
    return True


def has_hex_prefix(input_str: str) -> bool:
    """Check if string value has hexa prefix.

    @param input_str: String value.
    @return: True is string value has hexa prefix.
    """
    return input_str.lower().startswith('0x')


def add_hex_prefix(input_str: str):  # type: ignore
    """Add 0x prefix to input string."""
    if has_hex_prefix(input_str):
        return input_str
    return '0x' + input_str


def to_int(input_str: str):  # type: ignore
    """Convert input string to int (JSON does not handle hex-formatted numbers...)."""
    try:
        # If conversion of int in base 10 fails, it's most likely a hex-formatted number
        int_val = int(input_str)
    except ValueError:
        try:
            int_val = int(input_str, 16)
        except Exception:
            raise Exception(f"{input_str} is not a number")
    return int_val


def str_to_int(string_val: str, base: int, default_val: int) -> int:
    """Convert string value to int.

    @param string_val: input value as string
    @param base: base of input value
    @param default_val: default value
    """
    try:
        integer_val = int(string_val, base)
    except ValueError:
        # Badly formatted log
        integer_val = default_val
    return integer_val
